/**
 * Site-wide constants.
 *
 * This module is imported by `astro.config.ts`, by Astro components, AND by the
 * test suite -- so it must stay free of Astro virtual modules (`astro:content`,
 * `astro:assets`) and of any browser or Node-only API.
 */

/**
 * The canonical production origin. This is the ONLY place the domain is
 * written. `astro.config.ts` feeds it to `site`, and every canonical URL,
 * sitemap entry, and JSON-LD `@id` derives from `Astro.site` at render time.
 *
 * Never hard-code the domain anywhere else -- `tests/seo/urls.spec.ts` fails
 * the build if a built page contains a hard-coded origin outside this constant.
 */
export const SITE_URL = 'https://maxpattillo.com';

export const SITE_NAME = 'Max Pattillo';

/**
 * Where this site's source lives. Consumed by `/open-source/`, which is the
 * single place the repository is linked from; the footer's "Source" link points
 * at that page rather than at GitHub.
 *
 * DELIBERATELY NOT IN `person.socialProfiles`. That array feeds schema.org
 * `sameAs`, which asserts "this URL is another profile of this same person".
 * A code repository is not a profile of a human being, and putting it there
 * would make a false entity-resolution claim on every page — the exact failure
 * the note on `socialProfiles` in person.ts warns about.
 */
export const SOURCE_REPO_URL = 'https://github.com/maxpattillo/maxpattillosite';

/**
 * Fallback social share image, relative to the site root. Used whenever a page
 * does not supply its own. Must exist in `public/` at the referenced path --
 * `tests/seo/metadata.spec.ts` checks that it was actually emitted to `dist/`.
 *
 * GENERATED, AND COMMITTED. Built by `scripts/generate-og.mjs` (`pnpm og`) from
 * the same design tokens and the same bean as the site itself. Do not edit the
 * PNG by hand; edit the generator and re-run it.
 */
export const DEFAULT_OG_IMAGE = '/og/default.png';

/**
 * Describes what the card actually shows, not just who it is about.
 *
 * This is the text a screen reader reads out in place of a link preview, and
 * on most platforms it is the only description of the image there will ever be.
 * It was `'Bryce DeCora'`, which merely repeated the title next to it.
 */
export const DEFAULT_OG_IMAGE_ALT =
  'Bryce DeCora, co-founder of CloseBot — the name set in pixel type on a cream card, beside a coffee-bean mark.';

/**
 * Share-card dimensions.
 *
 * Declared as `og:image:width`/`height` so a crawler can reserve the right box
 * before it has fetched the image -- without them, Slack and X lay out the
 * unfurl twice and the preview visibly jumps.
 *
 * The generator reads these back: `tests/seo/og-cards.spec.ts` asserts they
 * match the card it actually renders, so the tags cannot describe an image
 * that is no longer that size.
 */
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;

/**
 * An article's own share card, relative to the site root.
 *
 * One card per published article, titled with that article's real `<h1>`.
 * Generated by `pnpm og` and committed; see `scripts/og-articles.mjs`.
 *
 * Defined here rather than inlined in the article route for the same reason
 * `articlePath` exists in utils/collections.ts: a template that builds its own
 * `/og/writing/${slug}.png` string is how one of them loses the extension and
 * starts pointing at nothing.
 */
export const articleOgImage = (slug: string) => `/og/writing/${slug}.png`;

/** Alt text for an article's share card, given its title. */
export const articleOgImageAlt = (title: string) =>
  `"${title}" — an article by Bryce DeCora, on a cream card in pixel type.`;

export const DEFAULT_LOCALE = 'en_US';

export const DEFAULT_LANG = 'en';

/**
 * URL policy. Encoded here so tests can assert against it rather than against a
 * hard-coded assumption.
 *
 * Three settings must agree or Cloudflare will redirect every indexed URL:
 *   1. astro.config.ts  build.format: 'directory'      -> emits dist/about/index.html
 *   2. astro.config.ts  trailingSlash: 'always'        -> links + canonicals emit /about/
 *   3. wrangler.jsonc   html_handling: force-trailing-slash
 *
 * Changing this after launch means redirecting every indexed URL. Don't.
 */
export const TRAILING_SLASH: 'always' | 'never' = 'always';

/**
 * Routes deliberately excluded from indexing.
 *
 * Single source of truth: consumed by the `@astrojs/sitemap` filter in
 * `astro.config.ts` AND by `<SEO>` when emitting the robots meta tag, so the
 * two can never disagree. `tests/seo/indexability.spec.ts` verifies that every
 * route listed here is both absent from the sitemap and carries `noindex`.
 *
 * Pathnames must be written in canonical form (leading + trailing slash).
 *
 * Empty for now: every page this site has is meant to be found. The 404 is
 * noindex through its own `robots` prop, not through this list.
 */
export const NOINDEX_ROUTES: readonly string[] = [];

/** True when the given pathname should be indexed and appear in the sitemap. */
export function isIndexable(pathname: string): boolean {
  return !NOINDEX_ROUTES.includes(normalizePathname(pathname));
}

/**
 * Coerce a pathname or absolute URL into the site's canonical path form:
 * lowercase, leading slash, trailing slash (root stays '/').
 */
export function normalizePathname(input: string): string {
  let path = input;

  // Accept a full URL as well as a bare pathname.
  if (/^https?:\/\//i.test(path)) {
    path = new URL(path).pathname;
  }

  // Strip query and hash -- they are never part of a canonical path.
  path = path.split(/[?#]/)[0] ?? '/';

  path = path.toLowerCase();

  if (!path.startsWith('/')) path = `/${path}`;

  // Paths naming a file (/robots.txt, /404.html, /og/default.png) are already
  // canonical. Appending a slash to them produces a URL that does not exist.
  if (/\.[a-z0-9]+$/i.test(path)) return path;

  if (TRAILING_SLASH === 'always') {
    if (!path.endsWith('/')) path = `${path}/`;
  } else if (path !== '/' && path.endsWith('/')) {
    path = path.slice(0, -1);
  }

  return path;
}
